
printpreview-simplify-page-checkbox =
    .label = Simplify Page
    .accesskey = i
    .tooltiptext = This page cannot be automatically simplified
printpreview-simplify-page-checkbox-enabled =
    .label = { printpreview-simplify-page-checkbox.label }
    .accesskey = { printpreview-simplify-page-checkbox.accesskey }
    .tooltiptext = Change layout for easier reading
printpreview-close =
    .label = Close
    .accesskey = C
printpreview-portrait =
    .label = Portrait
    .accesskey = o
printpreview-landscape =
    .label = Landscape
    .accesskey = L
printpreview-scale =
    .value = Scale:
    .accesskey = S
printpreview-shrink-to-fit =
    .label = Shrink To Fit
printpreview-custom =
    .label = Custom…
printpreview-print =
    .label = Print…
    .accesskey = P
printpreview-of =
    .value = of
printpreview-custom-scale-prompt-title = Custom Scale
printpreview-page-setup =
    .label = Page Setup…
    .accesskey = u
printpreview-page =
    .value = Page:
    .accesskey = a

printpreview-sheet-of-sheets = { $sheetNum } of { $sheetCount }


printpreview-percentage-value =
    .label = { $percent }%
printpreview-homearrow =
    .label = { $arrow }
    .tooltiptext = First page
printpreview-previousarrow =
    .label = { $arrow }
    .tooltiptext = Previous page
printpreview-nextarrow =
    .label = { $arrow }
    .tooltiptext = Next page
printpreview-endarrow =
    .label = { $arrow }
    .tooltiptext = Last page
printpreview-homearrow-button =
    .title = First page
printpreview-previousarrow-button =
    .title = Previous page
printpreview-nextarrow-button =
    .title = Next page
printpreview-endarrow-button =
    .title = Last page
